### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by flixlix** [gluap/pyess#16]
Good evening!
This is not really an issue as much as it's more of a question, but I figured this was the best place to get the support I needed.
I have an LG ESS at home and would like to connect it to Home Assistant.
This integration sounds like it's exactly what I need.
How would I go about installing this integration in my Home Assistant instance? Can you give me some steps or guidance to where I could get started?
Thanks in advance

**Comment by s-hager** [comment]
Hey! 
I think the steps described here in the [readme](https://github.com/gluap/pyess#mqtt-wrapper) should be what you need but it depends on your setup how you implement everything.
Basically you will need:
- A MQTT server
- Somewhere to run pyess
- The [MQTT integration](https://www.home-assistant.io/integrations/mqtt/) for Home Assistant

In my setup i run an Unraid Server so I could just pull a MQTT-Server Docker from the app repository.
Then i just had to set it up and create the credentials that will be required for the essmqtt service to connect to the server.

I actually made my own crude docker from essmqtt because it is the best solution when using Unraid in my opinion.
(In your setup you could maybe also use a systemd service like described in the [readme](https://github.com/gluap/pyess#essmqtt-as-systemd-service))
This is also where the MQTT autodiscovery has to be configured.
If you are interested in how i made the docker, i could clean up the code (it is not much) and make it available.
So now we have both the MQTT server and essmqtt running.

Then you are practically done and just need to configure the MQTT Integration in Home assistant and all your data (if you set up autodiscovery) should be visible in HA.

Let me know if you have questions...

**Comment by flixlix** [comment]
Thank you for your answer!
I have Home Assistant Operating System installed. How would I go about installing it then. I also have the "Terminal" Add-on installed, but it doesn't seem to want to run the python commands...

**Comment by gluap** [comment]
@flixlix it's easiest to set it up in HomeAssistant Core (which is less restricted than Homeassistant OS but requires a lot more background knowledge to operate). But in Homeassistant Core the normal install instructions apply.

If you want to run via HomeAssistant OS my guess would be that you could install the portainer addon to fetch a container which can run python (for instance one of the python containers) and set essmqtt up therein. Or you could write a Dockerfile to execute the build steps from the manual and build it from (one of the) Homeassistant OS Shels. I'm not sure though whether you can realistically expect to run the steps to get the API key from a container (UPNP might not work).

Disclaimer: I avoid Homeassistant OS because I find it very difficult to run custom software there. With homeassistant core I can just run my own docker containers, compile software on the host OS like I would normally do etc... whereas for homeassistant os everything.

The good news is that you dont have to run on the same machine as you run homeassistant OS from - you could take any other computer on your network - essmqtt should be able to run OS-independent.

**Comment by flixlix** [comment]
I finally was able to install it! Thank you both for your help :)
